version: '2'

services:
  db:
    image: mysql:5.7
# Descomentar las siguientes dos lineas (y comentar la de arriba) para usar mysql 8
    #image: mysql:8
    #command: --default-authentication-plugin=mysql_native_password
    
    restart: always
    mem_limit: 2000m
    
    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: passwordroot
      MYSQL_DATABASE: nombrebbdd

    volumes:
      - db_vol:/var/lib/mysql

    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  db_vol:
    external: true
